= Quarkus extension for Apache Cassandra®

image::https://maven-badges.herokuapp.com/maven-central/com.datastax.oss.quarkus/cassandra-quarkus-client/badge.svg[]

An Apache Cassandra(R) extension for Quarkus.

*You can find the latest version of the official documentation 
link:https://github.com/datastax/cassandra-quarkus/blob/master/documentation/src/main/asciidoc/cassandra.adoc[here].
Documentation for specific versions can be consulted via their respective release tags, e.g. 
link:https://github.com/datastax/cassandra-quarkus/blob/1.0.0-alpha1/documentation/src/main/asciidoc/cassandra.adoc[1.0.0-alpha1]*

== Getting the extension

The extension artifact is published in Maven central, under the group id
link:http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.datastax.oss%22.quarkus%22[com.datastax.oss.quarkus]:

[source,xml]
----
<dependency>
  <groupId>com.datastax.oss.quarkus</groupId>
  <artifactId>cassandra-quarkus-client</artifactId>
  <version>${cassandra-quarkus.version}</version>
</dependency>
----

== Compatibility

The extension is compatible with Quarkus version 1.7.1.Final and higher.

It requires Java 8 or higher.

== Useful links

* link:https://github.com/datastax/cassandra-quarkus/blob/master/documentation/src/main/asciidoc/cassandra.adoc[Quickstart guide]
* Bug tracking: link:https://github.com/datastax/cassandra-quarkus/issues[Issues]
* Quarkus link:https://groups.google.com/forum/#!forum/quarkus-dev[Mailing list]
* link:changelog/[Changelog]

== License

&copy; DataStax, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.


DataStax is a registered trademark of DataStax, Inc. and its subsidiaries in the United States 
and/or other countries.

Apache Cassandra, Apache, Tomcat, Lucene, Solr, Hadoop, Spark, TinkerPop, and Cassandra are 
trademarks of the [Apache Software Foundation](http://www.apache.org/) or its subsidiaries in
Canada, the United States and/or other countries. 
