[Dated: February 10, 2026]

This repository was temporarily offline following the confirmation of unauthorized activity within a limited number of our public Datastax GitHub repositories, listed below. Working with our internal incident response team, we took steps to contain, remediate and investigate the activity.

We followed established incident-response processes to review and to revert any unauthorized activity.

Required Actions: Collaborators who interacted with this repository between January 31, 2026, and February 3, 2026, rebase your branch onto the new `main`/ `master`. Do not merge `main` / `master` into your branch.

At Datastax, we remain committed to your security and to transparency within the open-source community.

Impacted Repositories:

* link:https://github.com/datastax/cassandra-quarkus[]
* link:https://github.com/datastax/graph-examples[]
* link:https://github.com/datastax/metric-collector-for-apache-cassandra[]
* link:https://github.com/datastax/native-protocol[]
* link:https://github.com/datastax/pulsar-sink[]

== Quarkus extension for Apache Cassandra®

image::https://maven-badges.herokuapp.com/maven-central/com.datastax.oss.quarkus/cassandra-quarkus-client/badge.svg[]

An Apache Cassandra(R) extension for Quarkus.

== Getting the extension

The extension artifact is published in Maven central, under the group id
link:http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.datastax.oss%22.quarkus%22[com.datastax.oss.quarkus]:

[source,xml]
----
<dependency>
  <groupId>com.datastax.oss.quarkus</groupId>
  <artifactId>cassandra-quarkus-client</artifactId>
  <version>${cassandra-quarkus.version}</version>
</dependency>
----

== Compatibility

The extension is compatible with Quarkus version `3.31.0` and higher.

Quarkus link:https://quarkus.io/blog/java-17/[requires Java17 or greater] since Quarkus 3.7 so this project does as well.

Quarkus 3.x requires at least Maven version `3.8.2` or higher to build correctly (see link:https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#maven-versions[Quarkus3 notes]).

== Useful links

* link:quickstart/README.adoc[Quickstart guide]
* Bug tracking: link:https://github.com/datastax/cassandra-quarkus/issues[Issues]
* Quarkus link:https://groups.google.com/forum/#!forum/quarkus-dev[Mailing list]
* link:changelog/[Changelog]

== License

&copy; DataStax, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.


DataStax is a registered trademark of DataStax, Inc. and its subsidiaries in the United States 
and/or other countries.

Apache Cassandra, Apache, Tomcat, Lucene, Solr, Hadoop, Spark, TinkerPop, and Cassandra are 
trademarks of the link:http://www.apache.org/[Apache Software Foundation] or its subsidiaries in
Canada, the United States and/or other countries. 
