= Cassandra Quarkus - Runtime Module

The Runtime module for an Apache Cassandra(R) extension for Quarkus.

== The Purpose of Runtime

This module contains classes used during the runtime of this extension.
The clients of the cassandra-extension should import this dependency in their 
applications.

== The QuarkusCqlSession

The main integration point with clients using this extension is the 
`QuarkusCqlSession` interface.

When clients want to connect to a Cassandra database, they should inject a 
`QuarkusCqlSession` instance in their code and execute all queries using it. 
The `QuarkusCqlSession` instance is produced as a `Singleton` and can be safely 
shared between all components of your application. Indeed it is usually 
considered an anti-pattern to create more than one session instance per 
application; to understand how to create and use a session object correctly, 
refer to the link:https://docs.datastax.com/en/developer/java-driver/latest/manual/core/#cql-session[Java driver documentation].

== Runtime Configuration

The `CassandraClientConnectionConfig` class provides the runtime settings to 
configure the `QuarkusCqlSession` bean.
