= Cassandra Quarkus - Integration tests

This module hosts integration tests for the Cassandra Quarkus extension.

It contains the following modules:

1. application: the application classes (no tests);
2. default: the main suite of integration tests;
3. metrics-microprofile: specific tests for metrics with MicroProfile;
4. metrics-disabled: specific tests for disabled metrics.

IMPORTANT: Integration tests in submodules of this module are executed as part of the Quarkus
Platform builds. For this reason they need to be deployed to Maven Central. Any changes in the
integration tests modules should be reflected in
https://github.com/quarkusio/quarkus-platform/blob/main/integration-tests/cassandra/invoked/root/pom.xml[this
Quarkus Platform POM].

== Running integration tests

To run the integration tests with regular packaging, simply execute:

    mvn clean verify
    
To run the integration tests in native mode:

    mvn clean verify -Dnative
    
Native mode requires that you point the environment variable `GRAALVM_HOME` to a valid GraalVM
installation root; also, Graal's `native-image` executable must have been previously installed with
`gu install native-image`.

When native mode is on, the build takes considerably longer to finish.
    