name: Build & test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java_version }}
    strategy:
      matrix:
        java_version:
          - '11'
          - '17'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java_version }}
          cache: 'maven'
      - name: Build & test
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          mvn verify
